# Generated by Django 2.2.11 on 2020-04-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.CharField(max_length=50, verbose_name='收货人')),
                ('phone', models.BigIntegerField(verbose_name='收货电话')),
                ('dom', models.CharField(max_length=50, verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '地址管理',
                'verbose_name_plural': '地址管理',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=50, verbose_name='微信唯一识别码')),
                ('session_key', models.CharField(max_length=50, verbose_name='会话秘钥')),
                ('address_management', models.ManyToManyField(blank=True, null=True, to='PersonnelManagement.Address', verbose_name='地址管理')),
            ],
            options={
                'verbose_name': '微信用户管理',
                'verbose_name_plural': '微信用户管理',
            },
        ),
    ]
