# Generated by Django 2.2.11 on 2020-04-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PersonnelManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='address_management',
            field=models.ManyToManyField(to='PersonnelManagement.Address', verbose_name='地址管理'),
        ),
    ]
