# Generated by Django 2.2.11 on 2020-03-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜品分类')),
            ],
            options={
                'verbose_name_plural': '菜品分类',
                'verbose_name': '菜品分类',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜品名称')),
                ('price', models.FloatField(verbose_name='价格')),
                ('discount_price', models.FloatField(blank=True, verbose_name='折扣价格')),
                ('img', models.ImageField(upload_to='dishes/', verbose_name='菜品图片')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.FoodClassification')),
            ],
            options={
                'verbose_name_plural': '菜品',
                'verbose_name': '菜品',
            },
        ),
    ]
