# Generated by Django 2.2.11 on 2020-03-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_dishes_shelves_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishes',
            name='discount_price',
            field=models.FloatField(blank=True, null=True, verbose_name='折扣价格'),
        ),
    ]
